Repository monewping/Heartsping, pull requests merged in 2025-07, with the labels that each got.

#37 Feat#31 - Global 패키지 하위 구조 작성
  .coderabbit.yml
  src/main/java/org/project/monewping/global/base/BaseEntity.java
  src/main/java/org/project/monewping/global/base/BaseUpdatableEntity.java
  src/main/java/org/project/monewping/global/dto/CursorPageResponse.java
  src/main/java/org/project/monewping/global/dto/ErrorResponse.java
Labels: Feature, Settings

#38 [Feat/article] 뉴스 기사 뷰 등록
  build.gradle
  src/main/java/org/project/monewping/domain/article/controller/ArticleController.java
  src/main/java/org/project/monewping/domain/article/dto/data/ArticleViewDto.java
  src/main/java/org/project/monewping/domain/article/dto/request/ArticleSaveRequest.java
  src/main/java/org/project/monewping/domain/article/entity/ArticleViews.java
  src/main/java/org/project/monewping/domain/article/entity/Articles.java
  src/main/java/org/project/monewping/domain/article/entity/Interest.java
  src/main/java/org/project/monewping/domain/article/exception/ArticleNotFoundException.java
  src/main/java/org/project/monewping/domain/article/exception/DuplicateArticleException.java
  src/main/java/org/project/monewping/domain/article/exception/DuplicateArticleViewsException.java
  src/main/java/org/project/monewping/domain/article/exception/InterestNotFoundException.java
  src/main/java/org/project/monewping/domain/article/fetcher/ArticleFetcher.java
  src/main/java/org/project/monewping/domain/article/fetcher/RestTemplateConfig.java
  src/main/java/org/project/monewping/domain/article/fetcher/naver/NaverArticleFetcher.java
  src/main/java/org/project/monewping/domain/article/fetcher/naver/dto/NaverNewsItem.java
  src/main/java/org/project/monewping/domain/article/fetcher/naver/dto/NaverNewsResponse.java
  src/main/java/org/project/monewping/domain/article/mapper/ArticleViewsMapper.java
  src/main/java/org/project/monewping/domain/article/mapper/ArticlesMapper.java
  src/main/java/org/project/monewping/domain/article/repository/ArticleViewsRepository.java
  src/main/java/org/project/monewping/domain/article/repository/ArticlesRepository.java
  src/main/java/org/project/monewping/domain/article/repository/InterestRepository.java
  src/main/java/org/project/monewping/domain/article/service/ArticleViewsService.java
  src/main/java/org/project/monewping/domain/article/service/ArticleViewsServiceImpl.java
  src/main/java/org/project/monewping/domain/article/service/ArticlesService.java
  src/main/java/org/project/monewping/domain/article/service/ArticlesServiceImpl.java
  src/main/java/org/project/monewping/global/base/BaseEntity.java
  src/main/java/org/project/monewping/global/config/JpaAuditingConfig.java
  src/main/java/org/project/monewping/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yaml
  src/test/java/org/project/monewping/domain/article/controller/ArticlesControllerTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/NaverArticleFetcher.java
  src/test/java/org/project/monewping/domain/article/service/ArticleViewsServiceTest.java
  src/test/java/org/project/monewping/domain/article/service/ArticlesServiceTest.java
  src/test/java/org/project/monewping/domain/user/Integration/UserIntegrationTest.java
Labels: Feature

#46 [Feat/notification] 알림 등록과 알림 목록 조회
  build.gradle
  src/main/java/org/project/monewping/domain/notification/controller/NotificationController.java
  src/main/java/org/project/monewping/domain/notification/dto/CursorPageResponseNotificationDto.java
  src/main/java/org/project/monewping/domain/notification/dto/NotificationDto.java
  src/main/java/org/project/monewping/domain/notification/entity/Notification.java
  src/main/java/org/project/monewping/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/org/project/monewping/domain/notification/exception/UnsupportedResourceTypeException.java
  src/main/java/org/project/monewping/domain/notification/mapper/NotificationMapper.java
  src/main/java/org/project/monewping/domain/notification/repository/NotificationRepository.java
  src/main/java/org/project/monewping/domain/notification/service/BasicNotificationService.java
  src/main/java/org/project/monewping/domain/notification/service/NotificationService.java
  src/main/java/org/project/monewping/global/base/BaseEntity.java
  src/main/java/org/project/monewping/global/config/SecurityConfig.java
  src/main/java/org/project/monewping/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yaml
  src/test/java/org/project/monewping/domain/notification/controller/NotificationControllerTest.java
  src/test/java/org/project/monewping/domain/notification/integration/NotificationIntegrationTest.java
  src/test/java/org/project/monewping/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/org/project/monewping/domain/notification/service/NotificationServiceTest.java
  src/test/resources/application-test.yaml
Labels: Feature

#50 [Feat/comment-delete] 댓글 삭제 기능
  src/main/java/org/project/monewping/domain/comment/controller/CommentController.java
  src/main/java/org/project/monewping/domain/comment/domain/Comment.java
  src/main/java/org/project/monewping/domain/comment/dto/CommentResponseDto.java
  src/main/java/org/project/monewping/domain/comment/exception/CommentDeleteException.java
  src/main/java/org/project/monewping/domain/comment/exception/CommentNotFoundException.java
  src/main/java/org/project/monewping/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/org/project/monewping/domain/comment/service/CommentService.java
  src/main/java/org/project/monewping/domain/comment/service/CommentServiceImpl.java
  src/main/java/org/project/monewping/global/exception/GlobalExceptionHandler.java
  src/test/java/org/project/monewping/domain/comment/controller/CommentControllerTest.java
  src/test/java/org/project/monewping/domain/comment/service/CommentServiceTest.java
Labels: Feature

#58 [Feat/article-list] 뉴스 기사 목록 조회
  build.gradle
  src/main/java/org/project/monewping/domain/article/controller/ArticleController.java
  src/main/java/org/project/monewping/domain/article/dto/data/ArticleDto.java
  src/main/java/org/project/monewping/domain/article/dto/data/ArticleViewDto.java
  src/main/java/org/project/monewping/domain/article/dto/request/ArticleSearchRequest.java
  src/main/java/org/project/monewping/domain/article/fetcher/ChosunRssFetcher.java
  src/main/java/org/project/monewping/domain/article/fetcher/HankyungRssFetcher.java
  src/main/java/org/project/monewping/domain/article/fetcher/YonhapRssFetcher.java
  src/main/java/org/project/monewping/domain/article/mapper/ArticlesMapper.java
  src/main/java/org/project/monewping/domain/article/repository/ArticleViewsRepository.java
  src/main/java/org/project/monewping/domain/article/repository/ArticlesRepository.java
  src/main/java/org/project/monewping/domain/article/repository/ArticlesRepositoryCustom.java
  src/main/java/org/project/monewping/domain/article/repository/ArticlesRepositoryImpl.java
  src/main/java/org/project/monewping/domain/article/scheduler/ArticleCollectorScheduler.java
  src/main/java/org/project/monewping/domain/article/service/ArticleViewsServiceImpl.java
  src/main/java/org/project/monewping/domain/article/service/ArticlesService.java
  src/main/java/org/project/monewping/domain/article/service/ArticlesServiceImpl.java
  src/main/java/org/project/monewping/global/exception/GlobalExceptionHandler.java
  src/test/java/org/project/monewping/domain/article/controller/ArticlesControllerTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/ArticleCollectorSchedulerTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/ChosunRssFetcherTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/HankyungRssFetcherTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/NaverArticleFetcherTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/YonhapRssFetcherTest.java
  src/test/java/org/project/monewping/domain/article/repository/ArticlesRepositoryTest.java
  src/test/java/org/project/monewping/domain/article/repository/QueryDSLTest.java
  src/test/java/org/project/monewping/domain/article/service/ArticlesServiceTest.java
Labels: Feature, Refactor

#60 [Feat/notification-single-confirm] 단일 알림 수정 기능
  src/main/java/org/project/monewping/domain/notification/controller/NotificationController.java
  src/main/java/org/project/monewping/domain/notification/dto/NotificationDto.java
  src/main/java/org/project/monewping/domain/notification/entity/Notification.java
  src/main/java/org/project/monewping/domain/notification/exception/InvalidCursorFormatException.java
  src/main/java/org/project/monewping/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/org/project/monewping/domain/notification/exception/UnsupportedResourceTypeException.java
  src/main/java/org/project/monewping/domain/notification/repository/NotificationRepository.java
  src/main/java/org/project/monewping/domain/notification/service/BasicNotificationService.java
  src/main/java/org/project/monewping/domain/notification/service/NotificationService.java
  src/main/java/org/project/monewping/domain/user/exception/UserNotFoundException.java
  src/main/java/org/project/monewping/global/exception/GlobalExceptionHandler.java
  src/test/java/org/project/monewping/domain/notification/controller/NotificationControllerTest.java
  src/test/java/org/project/monewping/domain/notification/integration/NotificationIntegrationTest.java
  src/test/java/org/project/monewping/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/org/project/monewping/domain/notification/service/NotificationServiceTest.java
Labels: Feature

#61 [Feat/interest delete] 관심사 삭제
  src/main/java/org/project/monewping/domain/interest/controller/InterestController.java
  src/main/java/org/project/monewping/domain/interest/exception/InterestDeletionException.java
  src/main/java/org/project/monewping/domain/interest/exception/InterestNotFoundException.java
  src/main/java/org/project/monewping/domain/interest/service/InterestService.java
  src/main/java/org/project/monewping/domain/interest/service/impl/InterestServiceImpl.java
  src/main/java/org/project/monewping/domain/user/exception/UserNotFoundException.java
  src/main/java/org/project/monewping/global/exception/GlobalExceptionHandler.java
  src/test/java/org/project/monewping/domain/interest/controller/InterestControllerTest.java
  src/test/java/org/project/monewping/domain/interest/integration/InterestDeleteIntegrationTest.java
  src/test/java/org/project/monewping/domain/interest/service/InterestServiceTest.java
  src/test/java/org/project/monewping/domain/notification/service/NotificationServiceTest.java
Labels: Feature, Test

#65 [Feat/article-backup-restore] 뉴스 기사 백업 및 복구
  .github/workflows/ci.yml
  .gitignore
  backup/news-2025-07-17.json
  build.gradle
  src/main/java/org/project/monewping/MonewpingApplication.java
  src/main/java/org/project/monewping/domain/article/controller/ArticleController.java
  src/main/java/org/project/monewping/domain/article/dto/response/ArticleRestoreResultDto.java
  src/main/java/org/project/monewping/domain/article/entity/Articles.java
  src/main/java/org/project/monewping/domain/article/mapper/ArticlesMapper.java
  src/main/java/org/project/monewping/domain/article/repository/ArticlesRepository.java
  src/main/java/org/project/monewping/domain/article/repository/ArticlesRepositoryImpl.java
  src/main/java/org/project/monewping/domain/article/scheduler/ArticleBackupScheduler.java
  src/main/java/org/project/monewping/domain/article/service/ArticleBackupService.java
  src/main/java/org/project/monewping/domain/article/service/ArticleBackupServiceImpl.java
  src/main/java/org/project/monewping/domain/article/service/ArticleRestoreService.java
  src/main/java/org/project/monewping/domain/article/service/ArticleRestoreServiceImpl.java
  src/main/java/org/project/monewping/domain/article/storage/ArticleBackupStorage.java
  src/main/java/org/project/monewping/domain/article/storage/LocalArticleBackupStorage.java
  src/main/resources/application.yaml
  src/test/java/org/project/monewping/domain/article/controller/ArticlesControllerTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/HankyungRssFetcherTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/YonhapRssFetcherTest.java
  src/test/java/org/project/monewping/domain/article/repository/ArticlesRepositoryTest.java
  src/test/java/org/project/monewping/domain/article/service/ArticleBackupServiceTest.java
  src/test/java/org/project/monewping/domain/article/service/ArticleRestoreServiceTest.java
Labels: Feature, Refactor, Settings

#67 [Feat/article-delete] 뉴스 기사 삭제
  src/main/java/org/project/monewping/domain/article/controller/ArticleController.java
  src/main/java/org/project/monewping/domain/article/entity/Articles.java
  src/main/java/org/project/monewping/domain/article/repository/ArticlesRepository.java
  src/main/java/org/project/monewping/domain/article/service/ArticlesService.java
  src/main/java/org/project/monewping/domain/article/service/ArticlesServiceImpl.java
  src/main/java/org/project/monewping/domain/interest/entity/Interest.java
  src/main/java/org/project/monewping/global/exception/GlobalExceptionHandler.java
  src/main/resources/ddl.sql
  src/test/java/org/project/monewping/domain/article/controller/ArticlesControllerTest.java
  src/test/java/org/project/monewping/domain/article/entity/ArticlesEntityTest.java
  src/test/java/org/project/monewping/domain/article/entity/ArticlesTest.java
  src/test/java/org/project/monewping/domain/article/integration/ArticlesIntegrationTest.java
  src/test/java/org/project/monewping/domain/article/service/ArticlesServiceTest.java
Labels: Feature, Test, Refactor

#69 [Feat/comment-update] 댓글 정보 수정 기능
  package-lock.json
  src/main/java/org/project/monewping/domain/comment/controller/CommentController.java
  src/main/java/org/project/monewping/domain/comment/domain/Comment.java
  src/main/java/org/project/monewping/domain/comment/dto/CommentRegisterRequestDto.java
  src/main/java/org/project/monewping/domain/comment/dto/CommentUpdateRequestDto.java
  src/main/java/org/project/monewping/domain/comment/mapper/CommentMapperImpl.java
  src/main/java/org/project/monewping/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/org/project/monewping/domain/comment/repository/CommentRepository.java
  src/main/java/org/project/monewping/domain/comment/service/CommentService.java
  src/main/java/org/project/monewping/domain/comment/service/CommentServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/org/project/monewping/domain/comment/controller/CommentControllerTest.java
  src/test/java/org/project/monewping/domain/comment/repository/CommentQueryDSLTest.java
  src/test/java/org/project/monewping/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/org/project/monewping/domain/comment/service/CommentServiceTest.java
Labels: Feature

#70 [Feat/comment-like] 댓글 좋아요 등록 및 취소 기능
  src/main/java/org/project/monewping/domain/comment/controller/CommentController.java
  src/main/java/org/project/monewping/domain/comment/controller/CommentLikeController.java
  src/main/java/org/project/monewping/domain/comment/domain/CommentLike.java
  src/main/java/org/project/monewping/domain/comment/dto/CommentRegisterRequestDto.java
  src/main/java/org/project/monewping/domain/comment/dto/CommentResponseDto.java
  src/main/java/org/project/monewping/domain/comment/exception/CommentLikeAlreadyExistsException.java
  src/main/java/org/project/monewping/domain/comment/exception/CommentLikeNotFoundException.java
  src/main/java/org/project/monewping/domain/comment/mapper/CommentMapper.java
  src/main/java/org/project/monewping/domain/comment/mapper/CommentMapperImpl.java
  src/main/java/org/project/monewping/domain/comment/repository/CommentCustomRepository.java
  src/main/java/org/project/monewping/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/org/project/monewping/domain/comment/repository/CommentLikeRepository.java
  src/main/java/org/project/monewping/domain/comment/service/CommentLikeService.java
  src/main/java/org/project/monewping/domain/comment/service/CommentService.java
  src/main/java/org/project/monewping/domain/comment/service/CommentServiceImpl.java
  src/main/java/org/project/monewping/global/exception/GlobalExceptionHandler.java
  src/test/java/org/project/monewping/domain/comment/controller/CommentControllerTest.java
  src/test/java/org/project/monewping/domain/comment/controller/CommentLikeControllerTest.java
  src/test/java/org/project/monewping/domain/comment/repository/CommentQueryDSLTest.java
  src/test/java/org/project/monewping/domain/comment/service/CommentLikeServiceTest.java
  src/test/java/org/project/monewping/domain/comment/service/CommentServiceTest.java
Labels: Feature

#63 [Fix/remove security user] 사용자 도메인 Spring Security 제거
  build.gradle
  src/main/java/org/project/monewping/domain/user/service/UserService.java
  src/main/java/org/project/monewping/global/config/SecurityConfig.java
  src/test/java/org/project/monewping/domain/interest/controller/InterestControllerTest.java
  src/test/java/org/project/monewping/domain/user/integration/UserIntegrationTest.java
  src/test/java/org/project/monewping/domain/user/service/UserServiceTest.java
  src/test/resources/application-test.yaml
Labels: Test

#76 [refactor/comment] 댓글 등록 기능
  backup/articles-2025-07-20.json
  src/main/java/org/project/monewping/domain/comment/controller/CommentController.java
  src/main/java/org/project/monewping/domain/comment/dto/CommentResponseDto.java
  src/main/java/org/project/monewping/domain/comment/mapper/CommentMapperImpl.java
  src/main/java/org/project/monewping/domain/comment/service/CommentService.java
  src/main/java/org/project/monewping/domain/comment/service/CommentServiceImpl.java
  src/test/java/org/project/monewping/domain/comment/controller/CommentControllerTest.java
  src/test/java/org/project/monewping/domain/comment/service/CommentServiceTest.java
Labels: Refactor

#80 refactor #16: 댓글 좋아요 기능 리팩토링
  src/main/java/org/project/monewping/domain/comment/controller/CommentLikeController.java
  src/main/java/org/project/monewping/domain/comment/service/CommentServiceImpl.java
  src/test/java/org/project/monewping/domain/comment/controller/CommentLikeControllerTest.java
Labels: Refactor

#84 [Fix-notification-confirm] 전체 알림 수정 후, updatedAt 필드 업데이트 누락 수정
  src/main/java/org/project/monewping/domain/notification/repository/NotificationRepository.java
  src/main/java/org/project/monewping/domain/notification/service/BasicNotificationService.java
Labels: bug fix

#85 [Refactor/article-view] 뉴스 기사 수집 및 무한 스크롤
  build.gradle
  src/main/java/org/project/monewping/MonewpingApplication.java
  src/main/java/org/project/monewping/domain/article/dto/data/NaverNewsItem.java
  src/main/java/org/project/monewping/domain/article/dto/request/ArticleSaveRequest.java
  src/main/java/org/project/monewping/domain/article/dto/response/NaverNewsResponse.java
  src/main/java/org/project/monewping/domain/article/entity/Articles.java
  src/main/java/org/project/monewping/domain/article/fetcher/ArticleFetcher.java
  src/main/java/org/project/monewping/domain/article/fetcher/ChosunRssFetcher.java
  src/main/java/org/project/monewping/domain/article/fetcher/HankyungRssFetcher.java
  src/main/java/org/project/monewping/domain/article/fetcher/HtmlCleaner.java
  src/main/java/org/project/monewping/domain/article/fetcher/NaverArticleFetcher.java
  src/main/java/org/project/monewping/domain/article/fetcher/RssArticleFetcher.java
  src/main/java/org/project/monewping/domain/article/fetcher/YonhapRssFetcher.java
  src/main/java/org/project/monewping/domain/article/mapper/ArticlesMapper.java
  src/main/java/org/project/monewping/domain/article/repository/ArticlesRepository.java
  src/main/java/org/project/monewping/domain/article/repository/ArticlesRepositoryImpl.java
  src/main/java/org/project/monewping/domain/article/scheduler/ArticleCollectorScheduler.java
  src/main/java/org/project/monewping/domain/article/service/ArticlesService.java
  src/main/java/org/project/monewping/domain/article/service/impl/ArticleBackupServiceImpl.java
  src/main/java/org/project/monewping/domain/article/service/impl/ArticleRestoreServiceImpl.java
  src/main/java/org/project/monewping/domain/article/service/impl/ArticleViewsServiceImpl.java
  src/main/java/org/project/monewping/domain/article/service/impl/ArticlesServiceImpl.java
  src/main/java/org/project/monewping/domain/comment/controller/CommentController.java
  src/main/java/org/project/monewping/domain/comment/repository/CommentCustomRepository.java
  src/main/java/org/project/monewping/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/org/project/monewping/domain/comment/service/CommentService.java
  src/main/java/org/project/monewping/domain/comment/service/CommentServiceImpl.java
  src/main/java/org/project/monewping/domain/interest/entity/Interest.java
  src/main/java/org/project/monewping/domain/interest/repository/KeywordRepository.java
  src/main/java/org/project/monewping/global/dto/CursorPageResponse.java
  src/main/resources/ddl.sql
  src/test/java/org/project/monewping/domain/article/entity/ArticlesEntityTest.java
  src/test/java/org/project/monewping/domain/article/entity/ArticlesTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/ArticleCollectorSchedulerTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/ChosunRssFetcherTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/HankyungRssFetcherTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/NaverArticleFetcherTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/RssArticleFetcherTest.java
  src/test/java/org/project/monewping/domain/article/fetcher/YonhapRssFetcherTest.java
  src/test/java/org/project/monewping/domain/article/scheduler/ArticleSchedulerTest.java
  src/test/java/org/project/monewping/domain/article/service/ArticleBackupServiceTest.java
  src/test/java/org/project/monewping/domain/article/service/ArticleRestoreServiceTest.java
  src/test/java/org/project/monewping/domain/article/service/ArticleViewsServiceTest.java
  src/test/java/org/project/monewping/domain/article/service/ArticlesServiceTest.java
  src/test/java/org/project/monewping/domain/article/storage/ArticleBackupStorageTest.java
  src/test/java/org/project/monewping/domain/comment/controller/CommentControllerTest.java
  src/test/java/org/project/monewping/domain/comment/repository/CommentQueryDSLTest.java
  src/test/java/org/project/monewping/domain/comment/service/CommentServiceTest.java
Labels: Feature, Test, Refactor

#87 [Refactor/notification-list] 알림 목록 조회 리팩토링
  src/main/java/org/project/monewping/domain/notification/repository/NotificationRepository.java
  src/main/java/org/project/monewping/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/org/project/monewping/domain/notification/repository/NotificationRepositoryCustomImpl.java
  src/main/java/org/project/monewping/domain/notification/service/BasicNotificationService.java
  src/test/java/org/project/monewping/domain/notification/integration/NotificationIntegrationTest.java
  src/test/java/org/project/monewping/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/org/project/monewping/domain/notification/service/NotificationServiceTest.java
Labels: Test, Refactor

#94 chore: Github Actions를 통한 PR 테스트 커버리지 측정 환경용 MongoDB 서비스 추가
  .github/workflows/ci.yml
Labels: Deployment

#90 [Refactor/comment delete] 댓글 삭제 리팩토링
  src/main/java/org/project/monewping/domain/article/entity/Articles.java
  src/main/java/org/project/monewping/domain/comment/domain/Comment.java
  src/main/java/org/project/monewping/domain/comment/service/CommentServiceImpl.java
  src/test/java/org/project/monewping/domain/comment/service/CommentServiceTest.java
Labels: Refactor

#100 [Refactor/comment like handler] 댓글 좋아요 리팩토링
  src/main/java/org/project/monewping/domain/comment/controller/CommentController.java
  src/main/java/org/project/monewping/domain/comment/domain/Comment.java
  src/main/java/org/project/monewping/domain/comment/exception/CommentLikeAlreadyExistsException.java
  src/main/java/org/project/monewping/domain/comment/exception/CommentLikeNotFoundException.java
  src/main/java/org/project/monewping/domain/comment/mapper/CommentMapper.java
  src/main/java/org/project/monewping/domain/comment/mapper/CommentMapperImpl.java
  src/main/java/org/project/monewping/domain/comment/repository/CommentLikeRepository.java
  src/main/java/org/project/monewping/domain/comment/service/CommentLikeService.java
  src/main/java/org/project/monewping/domain/comment/service/CommentService.java
  src/main/java/org/project/monewping/domain/comment/service/CommentServiceImpl.java
  src/main/java/org/project/monewping/global/exception/GlobalExceptionHandler.java
  src/test/java/org/project/monewping/domain/comment/controller/CommentControllerTest.java
  src/test/java/org/project/monewping/domain/comment/controller/CommentLikeControllerTest.java
  src/test/java/org/project/monewping/domain/comment/service/CommentLikeServiceTest.java
  src/test/java/org/project/monewping/domain/comment/service/CommentServiceTest.java
Labels: Refactor

#98 [Feat/notification-create] 알림 등록 통합 구현
  src/main/java/org/project/monewping/domain/article/scheduler/ArticleCollectorScheduler.java
  src/main/java/org/project/monewping/domain/article/service/impl/ArticlesServiceImpl.java
  src/main/java/org/project/monewping/domain/comment/service/CommentLikeService.java
  src/main/java/org/project/monewping/domain/comment/service/CommentServiceImpl.java
  src/main/java/org/project/monewping/domain/interest/repository/SubscriptionRepository.java
  src/main/java/org/project/monewping/domain/notification/batch/NotificationDeletionScheduler.java
  src/main/java/org/project/monewping/domain/notification/controller/NotificationController.java
  src/main/java/org/project/monewping/domain/notification/dto/request/CreateNotificationRequestDto.java
  src/main/java/org/project/monewping/domain/notification/entity/Notification.java
  src/main/java/org/project/monewping/domain/notification/exception/UnsupportedResourceTypeException.java
  src/main/java/org/project/monewping/domain/notification/repository/NotificationRepository.java
  src/main/java/org/project/monewping/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/org/project/monewping/domain/notification/service/BasicNotificationService.java
  src/main/java/org/project/monewping/domain/notification/service/NotificationService.java
  src/main/java/org/project/monewping/global/exception/GlobalExceptionHandler.java
  src/main/resources/ddl.sql
  src/test/java/org/project/monewping/domain/article/scheduler/ArticleSchedulerTest.java
  src/test/java/org/project/monewping/domain/article/service/ArticlesServiceTest.java
  src/test/java/org/project/monewping/domain/comment/service/CommentLikeServiceTest.java
  src/test/java/org/project/monewping/domain/comment/service/CommentServiceTest.java
  src/test/java/org/project/monewping/domain/notification/controller/NotificationControllerTest.java
  src/test/java/org/project/monewping/domain/notification/integration/NotificationIntegrationTest.java
  src/test/java/org/project/monewping/domain/notification/repository/NotificationQueryDSLTest.java
  src/test/java/org/project/monewping/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/org/project/monewping/domain/notification/service/NotificationDeletionSchedulerTest.java
  src/test/java/org/project/monewping/domain/notification/service/NotificationServiceTest.java
Labels: Feature, Test

#104 [Refactor/notification] NotificationService 구현체 클래스 이름 수정
  src/main/java/org/project/monewping/domain/notification/service/NotificationServiceImpl.java
  src/test/java/org/project/monewping/domain/notification/service/NotificationServiceTest.java
Labels: Refactor

#101 [Feat/user nickname update] 사용자 정보 수정
  src/main/java/org/project/monewping/domain/user/controller/UserController.java
  src/main/java/org/project/monewping/domain/user/domain/User.java
  src/main/java/org/project/monewping/domain/user/dto/request/UserNicknameUpdateRequest.java
  src/main/java/org/project/monewping/domain/user/service/UserService.java
  src/main/java/org/project/monewping/domain/useractivity/service/UserActivityService.java
  src/main/java/org/project/monewping/domain/useractivity/service/UserActivityServiceImpl.java
  src/test/java/org/project/monewping/domain/user/controller/UserControllerSliceTest.java
  src/test/java/org/project/monewping/domain/user/integration/UserIntegrationTest.java
  src/test/java/org/project/monewping/domain/user/service/UserServiceTest.java
  src/test/java/org/project/monewping/domain/useractivity/controller/UserActivityControllerSliceTest.java
Labels: Feature

#105 [refactor] #31: 스프링 부트 버전 통일
  src/main/resources/application.yaml
Labels: Settings

#108 [Feat/user delete] 사용자 논리/물리 삭제
  src/main/java/org/project/monewping/domain/user/controller/UserController.java
  src/main/java/org/project/monewping/domain/user/entity/User.java
  src/main/java/org/project/monewping/domain/user/exception/UserAlreadyDeletedException.java
  src/main/java/org/project/monewping/domain/user/exception/UserDeleteException.java
  src/main/java/org/project/monewping/domain/user/mapper/UserMapper.java
  src/main/java/org/project/monewping/domain/user/repository/UserDeletionRepository.java
  src/main/java/org/project/monewping/domain/user/repository/UserDeletionRepositoryImpl.java
  src/main/java/org/project/monewping/domain/user/service/UserService.java
  src/main/java/org/project/monewping/domain/useractivity/document/UserActivityDocument.java
  src/main/java/org/project/monewping/domain/useractivity/dto/UserActivityDto.java
  src/main/java/org/project/monewping/domain/useractivity/mapper/UserActivityMapper.java
  src/main/java/org/project/monewping/domain/useractivity/service/UserActivityService.java
  src/main/java/org/project/monewping/domain/useractivity/service/UserActivityServiceImpl.java
  src/main/java/org/project/monewping/global/exception/GlobalExceptionHandler.java
  src/test/java/org/project/monewping/domain/article/repository/QueryDSLTest.java
  src/test/java/org/project/monewping/domain/comment/service/CommentLikeServiceTest.java
  src/test/java/org/project/monewping/domain/interest/integration/InterestIntegrationTest.java
  src/test/java/org/project/monewping/domain/interest/repository/InterestQueryDSLTest.java
  src/test/java/org/project/monewping/domain/interest/repository/InterestRepositoryCustomImplTest.java
  src/test/java/org/project/monewping/domain/interest/repository/SubscriptionRepositoryTest.java
  src/test/java/org/project/monewping/domain/interest/service/impl/SubscriptionServiceImplTest.java
  src/test/java/org/project/monewping/domain/notification/integration/NotificationIntegrationTest.java
  src/test/java/org/project/monewping/domain/notification/repository/NotificationQueryDSLTest.java
  src/test/java/org/project/monewping/domain/user/entity/UserTest.java
  src/test/java/org/project/monewping/domain/user/repository/UserDeletionRepositoryImplTest.java
  src/test/java/org/project/monewping/domain/user/repository/UserRepositorySliceTest.java
  src/test/java/org/project/monewping/domain/user/service/UserServiceTest.java
Labels: Feature
